### ISSUE TITLE
Vehicle offset and vehicle mismatch

### ISSUE THREAD

**Issue by yindong97** [stevenwudi/6DVNET#1]
## ❓ Questions and Help
Thank you for your work!
I used your code to run and found that there are quite a few deviations between the model and the real vehicle. There also are some problems about the vehicle model matching. I don't know if you have encountered this problem and have a solution?

**Comment by stevenwudi** [comment]
Hey @yindong97   Thank you for your interest in my work.
I am afraid that the current repo doesn't generate the winning solution of the ApolloScape 3D car Instance Understanding challenge.
However, a very under-documented repo does have the winning solution code:
https://github.com/stevenwudi/ApolloScape_InstanceSeg

Hope it helps. 
Best

**Comment by Haotian-Zhang** [comment]
> ## ❓ Questions and Help
> Thank you for your work!
> I used your code to run and found that there are quite a few deviations between the model and the real vehicle. There also are some problems about the vehicle model matching. I don't know if you have encountered this problem and have a solution?

Hi, Yindong, I wonder if you have obtained similar results from the code, maybe not the same as the winning solution? From my side, the results seem very terrible...
