### ISSUE TITLE
nvidia-docker：未找到命令

### ISSUE THREAD

**Issue by enhenghengheng** [stevenwudi/6DVNET#8]
运行这句时
nvidia-docker build -t maskrcnn-benchmark --build-arg CUDA=10.0 --build-arg CUDNN=7 docker/ 
报错，请问该如何解决？

**Comment by daaariiich** [comment]
I have the same problem.
Which version of TorchVision should I use?
The latest version requires PyTorch 1.2 or newer.

Step 16/19 : RUN git clone https://github.com/pytorch/vision.git  && cd vision  && python setup.py install
 ---> Running in ecf585d14d1c
Cloning into 'vision'...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Building wheel torchvision-0.5.0a0+d2c763e
running install
running bdist_egg
running egg_info
creating torchvision.egg-info
writing torchvision.egg-info/PKG-INFO
writing dependency_links to torchvision.egg-info/dependency_links.txt
writing requirements to torchvision.egg-info/requires.txt
writing top-level names to torchvision.egg-info/top_level.txt
writing manifest file 'torchvision.egg-info/SOURCES.txt'
reading manifest file 'torchvision.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'torchvision.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/torchvision
copying torchvision/utils.py -> build/lib.linux-x86_64-3.6/torchvision
copying torchvision/__init__.py -> build/lib.linux-x86_64-3.6/torchvision
copying torchvision/version.py -> build/lib.linux-x86_64-3.6/torchvision
copying torchvision/extension.py -> build/lib.linux-x86_64-3.6/torchvision
creating build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/_functional_video.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/transforms.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/functional_tensor.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/_transforms_video.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
copying torchvision/transforms/functional.py -> build/lib.linux-x86_64-3.6/torchvision/transforms
creating build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/utils.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/alexnet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/mobilenet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/vgg.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/squeezenet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/shufflenetv2.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/resnet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/mnasnet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/densenet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/_utils.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/googlenet.py -> build/lib.linux-x86_64-3.6/torchvision/models
copying torchvision/models/inception.py -> build/lib.linux-x86_64-3.6/torchvision/models
creating build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/roi_align.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/boxes.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/roi_pool.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/poolers.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/deform_conv.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/_register_onnx_ops.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/_utils.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/misc.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/ps_roi_align.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/new_empty_tensor.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/ps_roi_pool.py -> build/lib.linux-x86_64-3.6/torchvision/ops
copying torchvision/ops/feature_pyramid_network.py -> build/lib.linux-x86_64-3.6/torchvision/ops
creating build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/stl10.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/kinetics.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/utils.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/fakedata.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/sbd.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/celeba.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/ucf101.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/phototour.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/semeion.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/omniglot.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/sbu.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/hmdb51.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/vision.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/flickr.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/video_utils.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/voc.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/caltech.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/folder.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/svhn.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/imagenet.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/coco.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/lsun.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/cifar.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/mnist.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/cityscapes.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
copying torchvision/datasets/usps.py -> build/lib.linux-x86_64-3.6/torchvision/datasets
creating build/lib.linux-x86_64-3.6/torchvision/io
copying torchvision/io/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/io
copying torchvision/io/_video_opt.py -> build/lib.linux-x86_64-3.6/torchvision/io
copying torchvision/io/video.py -> build/lib.linux-x86_64-3.6/torchvision/io
creating build/lib.linux-x86_64-3.6/torchvision/models/video
copying torchvision/models/video/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/models/video
copying torchvision/models/video/resnet.py -> build/lib.linux-x86_64-3.6/torchvision/models/video
creating build/lib.linux-x86_64-3.6/torchvision/models/segmentation
copying torchvision/models/segmentation/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/models/segmentation
copying torchvision/models/segmentation/fcn.py -> build/lib.linux-x86_64-3.6/torchvision/models/segmentation
copying torchvision/models/segmentation/_utils.py -> build/lib.linux-x86_64-3.6/torchvision/models/segmentation
copying torchvision/models/segmentation/deeplabv3.py -> build/lib.linux-x86_64-3.6/torchvision/models/segmentation
copying torchvision/models/segmentation/segmentation.py -> build/lib.linux-x86_64-3.6/torchvision/models/segmentation
creating build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/utils.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/mobilenet.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/shufflenetv2.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/resnet.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/googlenet.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
copying torchvision/models/quantization/inception.py -> build/lib.linux-x86_64-3.6/torchvision/models/quantization
creating build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/mask_rcnn.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/faster_rcnn.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/keypoint_rcnn.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/transform.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/rpn.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/roi_heads.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/_utils.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/generalized_rcnn.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/backbone_utils.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
copying torchvision/models/detection/image_list.py -> build/lib.linux-x86_64-3.6/torchvision/models/detection
creating build/lib.linux-x86_64-3.6/torchvision/datasets/samplers
copying torchvision/datasets/samplers/__init__.py -> build/lib.linux-x86_64-3.6/torchvision/datasets/samplers
copying torchvision/datasets/samplers/clip_sampler.py -> build/lib.linux-x86_64-3.6/torchvision/datasets/samplers
running build_ext
building 'torchvision._C' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/vision
creating build/temp.linux-x86_64-3.6/vision/torchvision
creating build/temp.linux-x86_64-3.6/vision/torchvision/csrc
creating build/temp.linux-x86_64-3.6/vision/torchvision/csrc/cpu
gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -W
strict-prototypes -fPIC -I/vision/torchvision/csrc -I/miniconda/envs/py36/lib/python3.6/site-packages/torch/include 
-I/miniconda/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/miniconda/envs/py36/lib/p
ython3.6/site-packages/torch/include/TH -I/miniconda/envs/py36/lib/python3.6/site-packages/torch/include/THC -I/mini
conda/envs/py36/include/python3.6m -c /vision/torchvision/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/vision/torc
hvision/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++1
1
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /vision/torchvision/csrc/vision.cpp:8:0:
/vision/torchvision/csrc/DeformConv.h:90:24: error: 'torch::autograd::AutogradContext' has not been declared
 using torch::autograd::AutogradContext;
                        ^
/vision/torchvision/csrc/DeformConv.h:95:39: error: expected template-name before '<' token
     : public torch::autograd::Function<DeformConv2dFunction> {
                                       ^
/vision/torchvision/csrc/DeformConv.h:95:39: error: expected '{' before '<' token
/vision/torchvision/csrc/DeformConv.h:95:39: error: expected unqualified-id before '<' token
error: command 'gcc' failed with exit status 1
The command '/bin/sh -c git clone https://github.com/pytorch/vision.git  && cd vision  && python setup.py install' r
eturned a non-zero code: 1

**Comment by stevenwudi** [comment]
Hey I have migrated to a better maintained repo in: https://github.com/stevenwudi/Kaggle_PKU_Baidu/
